
CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE VEICULO(
idVeiculo INT PRIMARY KEY IDENTITY(1,1),
numeroVeiculo CHAR(13) NOT NULL
);
GO

CREATE TABLE CLIENTE(
idCliente INT PRIMARY KEY IDENTITY(1,1),
idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
nomeCliente VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE MARCA(
idMarca INT PRIMARY KEY IDENTITY(1,1),
idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
nomeMarca VARCHAR(10) NOT NULL UNIQUE
);
GO

CREATE TABLE MODELO(
idModelo INT PRIMARY KEY IDENTITY(1,1),
idMarca INT FOREIGN KEY REFERENCES MARCA(idMarca),
nomeModelo VARCHAR(20) NOT NULL UNIQUE
);
GO