
CREATE DATABASE CLINICA;
GO

USE CLINICA;
GO

CREATE TABLE PET(
idPet INT PRIMARY KEY IDENTITY(1,1),
nomePet VARCHAR(20) NOT NULL UNIQUE,
tipoPet CHAR(13) NOT NULL UNIQUE,
dataNascimento VARCHAR(13) NOT NULL
);
GO

CREATE TABLE RACA(
idRaca INT PRIMARY KEY IDENTITY(1,1),
idPet INT FOREIGN KEY REFERENCES PET(idPet),
nomeRaca VARCHAR(10) NOT NULL
);
GO

CREATE TABLE DONOS(
idDonos INT PRIMARY KEY IDENTITY(1,1),
idPet INT FOREIGN KEY REFERENCES PET(idPet),
nomeDonos VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE VETERINARIO(
idVeterinario INT PRIMARY KEY IDENTITY(1,1),
idPet INT FOREIGN KEY REFERENCES PET(idPet),
nomeVeterinario VARCHAR(20) NOT NULL UNIQUE
);
GO