CREATE DATABASE SP_MEDICAL;
GO

USE SP_MEDICAL;
GO

CREATE TABLE CLINICA(
idClinica TINYINT PRIMARY KEY,
nomeClinica VARCHAR(20) NOT NULL UNIQUE,
endClinica VARCHAR(50) NOT NULL UNIQUE,
horarioAbertura CHAR(5) NOT NULL,
horarioFechamento CHAR(5) NOT NULL,
razaoSocial VARCHAR(20) NOT NULL
);
GO

CREATE TABLE ESPECIALIDADE(
idEspecialidade TINYINT PRIMARY KEY,
nomeEspecialidade VARCHAR(45) NOT NULL,
);
GO

CREATE TABLE PACIENTE(
idPaciente TINYINT PRIMARY KEY,
nomePaciente VARCHAR(15) NOT NULL UNIQUE,
emailPaciente VARCHAR (30) UNIQUE,
dataNascimento CHAR(10) NOT NULL,
telefonePaciente CHAR(13) UNIQUE,
rgPaciente CHAR(10) NOT NULL UNIQUE,
cpfPaciente CHAR(11) NOT NULL UNIQUE,
endPaciente VARCHAR(50) NOT NULL,
);
GO

CREATE TABLE MEDICO(
idMedico TINYINT PRIMARY KEY,
nomeMedico VARCHAR(20) NOT NULL UNIQUE,
idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
idEspecialidade TINYINT FOREIGN KEY REFERENCES ESPECIALIDADE(idEspecialidade),
emailMedico VARCHAR(30) UNIQUE,
cnpjMedico VARCHAR(20) NOT NULL UNIQUE,
razaoSocial VARCHAR(20) NOT NULL
);
GO

CREATE TABLE CONSULTA(
idConsulta TINYINT PRIMARY KEY,
idMedico TINYINT FOREIGN KEY REFERENCES MEDICO(idMedico),
idPaciente TINYINT FOREIGN KEY REFERENCES PACIENTE(idPaciente),
dataConsulta VARCHAR(16) NOT NULL,
situacao VARCHAR(10) NOT NULL
);
GO